apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: wp-labs
  labels:
    app: postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgresql