apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: wp-labs
type: Opaque
stringData:
  rabbitmq-user: "student"
  rabbitmq-password: "student_secure_rabbit_pass_change_in_prod"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-erlang-cookie
  namespace: wp-labs
type: Opaque
stringData:
  # 🎓 Must be consistent across all replicas. Generate once.
  cookie: "rabbitmq-lab-cookie-2024"