apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: wp-labs
type: Opaque
stringData:
  postgres-user: student
  postgres-password: student_secure_password
  postgres-db: wp_labs