apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: wp-labs
  labels:
    app: api
type: Opaque
stringData:
  DB_PASSWORD: "student_secure_password"
  REDIS_PASSWORD: "redis_secure_password_change_in_prod"

  JWT_ACCESS_SECRET: "super_secret_access_key_change_in_prod"
  JWT_REFRESH_SECRET: "super_secret_refresh_key_change_in_prod"

  CLIENT_ID: "your_client_id"
  CLIENT_SECRET: "your_client_secret"

  SMTP_PASS: "your_app_password"

  MINIO_ACCESS_KEY: "minio_admin"
  MINIO_SECRET_KEY: "minio_secure_password_change_in_prod"

  RABBITMQ_USER: "student"
  RABBITMQ_PASS: "student_secure_rabbit_pass_change_in_prod"

  MONGO_URI: "mongodb://student:student_secure_password@mongo.wp-labs.svc.cluster.local:27017/wp_labs?authSource=admin"
