apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: wp-labs
type: Opaque
stringData:
  mongo-root-user: student
  mongo-root-password: student_secure_password
  mongo-db: wp_labs