apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: wp-labs
  labels:
    app: web
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: web
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
